ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom0: /odom
    odom0_config: [false, false, false,
                   true, true, false,
                   false, false, false,
                   false, false, true,
                   true, true, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, false,
                  false, false, true]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

